<a href="https://colab.research.google.com/github/prakritipaul/mhcglobe/blob/main/prakriti_MHCglobe2024_3_19_5_33PM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Prakriti's 1st Attempt to Run Base Model on One-Hot Coded Features

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
!git clone https://github.com/prakritipaul/mhcglobe.git

Cloning into 'mhcglobe'...
remote: Enumerating objects: 639, done.
remote: Counting objects: 100% (90/90), done.
remote: Compressing objects: 100% (73/73), done.
remote: Total 639 (delta 43), reused 46 (delta 15), pack-reused 549
Receiving objects: 100% (639/639), 112.34 MiB | 11.21 MiB/s, done.
Resolving deltas: 100% (341/341), done.
Updating files: 100% (196/196), done.


In [ ]:
import sys
sys.path.append("/content/mhcglobe/src")

### Play around with classes in sequence_functions

#### PseudoSeq

In [ ]:
import sequence_functions
test_PseudoSeq = sequence_functions.PseudoSeq()

In [ ]:
type(test_PseudoSeq.pseudoseq)

In [ ]:
test_pseudoseq = test_Data.pseudoseq
test_pseudoseq

In [ ]:
# 14637
test_allel2seq = test_Data.allele2seq
test_allel2seq
# len(test_allel2seq)
# all(len(value) == 34 for value in test_allel2seq.values())

##### MHCName

In [ ]:
standard_allele_names = list(test_pseudoseq['allele'].unique())
len(standard_allele_names)

14637

In [ ]:
allele = "HLA-A*03:01"
allele = allele.replace('*', '').replace(':', '')
allele

'HLA-A0301'

In [ ]:
test_MHCName = sequence_functions.MHCName()

In [ ]:
def parse_allele(allele):
    """
    Parse allele name to match pseudosequence csv.
    """
    allele = allele.replace('*', '').replace(':', '')
    return(allele)

def is_same(standard_allele_names, query_allele):
    """
    If allele2 parsed matched an allele name in standard alleles
    list, return the allele1 name (from standard alleles). Else
    return allele2 name.
    """
    a_q = parse_allele(query_allele.replace('HLA-', ''))
    for allele1 in standard_allele_names:
        a1 = parse_allele(allele1.replace('HLA-', '')) ####### Make this into a dict to avoid n * n comparisons.
        if a1==a_q:
            return allele1
    else: # Keep allele the same as input.
        print(a1, a_q)
        return query_allele

# my guess
alleles_vct = ["HLA-A*03:01", "HLA-A*02:01", "HLA-A2402"]

# Creating mapping of allele input name to a standardized naming.
allele_dict = {}
for allele in alleles_vct:
    if allele not in allele_dict:
        allele_dict[allele] = is_same(standard_allele_names, allele)
[allele_dict[a] for a in alleles_vct]

# Output
allele_dict

{'HLA-A*03:01': 'HLA-A*03:01',
 'HLA-A*02:01': 'HLA-A*02:01',
 'HLA-A2402': 'HLA-A*24:02'}

#### SeqRepresentation

In [ ]:
test_SeqRepresentation = sequence_functions.SeqRepresentation("ONE_HOT")

In [ ]:
# Expected 1's on position 0
test_residue = "A"
test_one_hot = test_SeqRepresentation.one_hot(test_residue)
test_one_hot

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [ ]:
test_select_peptideencoding = test_SeqRepresentation.select_peptideencoding("BLOSUM62")
test_select_peptideencoding

list

In [ ]:
test_peptide = "ARDVAA"
test_encoded_peptide = test_SeqRepresentation.encode_peptide(test_peptide)
test_encoded_peptide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

In [ ]:
test_seq_to_15mer = sequence_functions.seq_to_15mer(test_encoded_peptide)
test_seq_to_15mer

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.

In [ ]:
## VIMP TEST!!!
# Came from 1st 3 entries in "mhcglobe_full_train_data.csv"
test_df_data = {"allele": ["HLA-A*03:01", "HLA-A*11:01", "HLA-A*03:01"],
                "peptide": ["EVMPVSMAK", "EVMPVSMAK", "KTFPPTEPK"],
                "measurement_value": [340.6333333333333, 17.14, 219.8166666666667]}
test_df = pd.DataFrame(test_df_data)

In [ ]:
test_df

allele    peptide  measurement_value
0  HLA-A*03:01  EVMPVSMAK         340.633333
1  HLA-A*11:01  EVMPVSMAK          17.140000
2  HLA-A*03:01  KTFPPTEPK         219.816667

In [ ]:
test_XY = sequence_functions.get_XY(test_df, "ONE_HOT")
len(test_XY)

2

In [ ]:
test_X_alleles = test_XY[0][0]
# 3 (because there are 3 alleles/peptides)
len(test_X_alleles)

test_X_peptides = test_XY[0][1]
# 3 (because there are 3 alleles/peptides)
len(test_X_peptides)

3

In [ ]:
# test_X_allele_1 = test_X_alleles[0]
# 34
# len(test_X_allele_1)
# test_X_allele_1

test_X_peptide_1 = test_X_peptides[0]
# 15
len(test_X_peptide_1)
# test_X_peptide_1

15

### Play around with classes in mhc_data


#### MHCData object (will contain pseudoseq etc.)

In [ ]:
import mhc_data

In [ ]:
# Contains both human and non-human
# BA + EL
test_pMHC_Data_both = mhc_data.pMHC_Data(only_EL=True, drop_duplicate_records=True)
test_pMHC_Data_both_data = test_pMHC_Data_both.data
test_pMHC_Data_both_data


allele       dataset measurement_inequality measurement_type  \
0        HLA-A*03:01          IEDB                      =               BA   
1        HLA-A*11:01          IEDB                      =               BA   
2        HLA-A*03:01          IEDB                      =               BA   
3        HLA-A*11:01          IEDB                      =               BA   
4        HLA-A*03:01          IEDB                      =               BA   
...              ...           ...                    ...              ...   
1229823  HLA-B*44:02  MHCFlury2_S1                      <               MA   
1229825  HLA-A*02:01  MHCFlury2_S1                      <               MA   
1229831  HLA-A*02:01  MHCFlury2_S1                      <               MA   
1229834  HLA-B*44:02  MHCFlury2_S1                      <               MA   
1229836  HLA-B*44:02  MHCFlury2_S1                      <               MA   

         measurement_value    peptide   Gene  is_ABC  is_human  
0               340.633333  EVMPVSMAK  HLA-A    True      True  
1                17.140000  EVMPVSMAK  HLA-A    True      True  
2               219.816667  KTFPPTEPK  HLA-A    True      True  
3               222.213333  KTFPPTEPK  HLA-A    True      True  
4                57.250000  RLYYDSMSY  HLA-A    True      True  
...                    ...        ...    ...     ...       ...  
1229823         100.000000  AETEKQVAL  HLA-B    True      True  
1229825         100.000000  NIFIGIVGV  HLA-A    True      True  
1229831         100.000000  SMMKNFFFV  HLA-A    True      True  
1229834         100.000000  EEQRAQQQL  HLA-B    True      True  
1229836         100.000000  EENMHDLQY  HLA-B    True      True  

[729538 rows x 9 columns]

In [ ]:
test_pMHC_Data_both.positives


allele       dataset measurement_inequality measurement_type  \
180874        H-2-Kd          IEDB                      <               SA   
180875   HLA-B*15:16          IEDB                      <               SA   
180876   HLA-B*15:16          IEDB                      <               SA   
180877   HLA-B*15:16          IEDB                      <               SA   
180878   HLA-B*14:02          IEDB                      <               SA   
...              ...           ...                    ...              ...   
1229823  HLA-B*44:02  MHCFlury2_S1                      <               MA   
1229825  HLA-A*02:01  MHCFlury2_S1                      <               MA   
1229831  HLA-A*02:01  MHCFlury2_S1                      <               MA   
1229834  HLA-B*44:02  MHCFlury2_S1                      <               MA   
1229836  HLA-B*44:02  MHCFlury2_S1                      <               MA   

         measurement_value    peptide   Gene  is_ABC  is_human  
180874               100.0  TYQRTRALV  H-2-K   False     False  
180875               100.0  VSYGSIVTY  HLA-B    True      True  
180876               100.0  LTDPSQRLV  HLA-B    True      True  
180877               100.0  YTIPPGHQV  HLA-B    True      True  
180878               100.0  DRYRRIHSL  HLA-B    True      True  
...                    ...        ...    ...     ...       ...  
1229823              100.0  AETEKQVAL  HLA-B    True      True  
1229825              100.0  NIFIGIVGV  HLA-A    True      True  
1229831              100.0  SMMKNFFFV  HLA-A    True      True  
1229834              100.0  EEQRAQQQL  HLA-B    True      True  
1229836              100.0  EENMHDLQY  HLA-B    True      True  

[553779 rows x 9 columns]

In [ ]:
non_zero_alleles = set()
for allele in test_dict:
  count = test_dict[allele]
  if count != 0:
    non_zero_alleles.add(allele)

In [ ]:
non_zero_alleles

In [ ]:
len(test_dict)

14637

### Playing around with saved model

In [ ]:
# sys.path.append("/content/mhcglobe/src/model/mhcglobe/full/model14_fold13_ONE_HOT_full")
sys.path.append("/content/mhcglobe/src/model/mhcglobe/init/model14_fold13_ONE_HOT_full")

In [ ]:
# model_dir = "/content/mhcglobe/model/mhcglobe/full/model14_fold13_ONE_HOT_full/"
model_dir = "/content/mhcglobe/model/mhcglobe/init/model14_fold13_ONE_HOT_init/"
eric_model_1 = tf.saved_model.load(model_dir)

# model_dir = "/content/mhcglobe/model/mhcglobe/init/model37_fold15_ONE_HOT_init"
# eric_model_2 = tf.saved_model.load(model_dir)

In [ ]:
for var in eric_model_1.variables:
    print(var.name, var.shape)

d1/kernel:0 (980, 256)
d1/bias:0 (256,)
d2/kernel:0 (1236, 512)
d2/bias:0 (512,)
d3/kernel:0 (512, 128)
d3/bias:0 (128,)
output/kernel:0 (128, 1)
output/bias:0 (1,)


In [ ]:
eric_model_1.signatures

_SignatureMap({'serving_default': <ConcreteFunction (*, peptide_input: TensorSpec(shape=(None, 15, 20), dtype=tf.float32, name='peptide_input'), mhc_input: TensorSpec(shape=(None, 34, 20), dtype=tf.float32, name='mhc_input')) -> Dict[['output', TensorSpec(shape=(None, 1), dtype=tf.float32, name='output')]] at 0x7D33B4BC9B70>})

In [ ]:
# ChatGPT

# Path to the directory containing the checkpoint files, without the file extension
checkpoint_path = "/content/mhcglobe/model/mhcglobe/full/model14_fold13_ONE_HOT_full/variables/"

# Create a CheckpointReader
reader = tf.train.load_checkpoint(checkpoint_path)

# List variable names and shapes
var_shapes = reader.get_variable_to_shape_map()
for name in var_shapes:
    print(f"Variable name: {name}, shape: {var_shapes[name]}")

### Attempt to load Eric's model and inspect contents - FAILURE

In [ ]:
import train_functions

In [ ]:
eric_model_1b = train_functions.load_trained_mhcglobe_model(model_path=model_dir)

In [ ]:
help(eric_model_1b)

In [ ]:
import tensorflow as tf

checkpoint_path = "/content/mhcglobe/model/mhcglobe/full/model14_fold13_ONE_HOT_full/variables/variables.data-00000-of-00002"

# Create a checkpoint reader
reader = tf.train.load_checkpoint(checkpoint_path)

# Get the variable names
variable_names = reader.get_variable_to_shape_map().keys()

# Print the variable names
for variable_name in variable_names:
  print(variable_name)

# Get the value of a variable
variable_value = reader.get_tensor(variable_name)

# Print the variable value
print(variable_value)

## Attempting to train model/use mhcglobe functions

In [ ]:
import mhcglobe

In [ ]:
test_ensemble = mhcglobe.ensemble(train_type="init")

In [ ]:
test_ensemble_base_models = test_ensemble.ensemble_base_models
test_ensemble_base_models

In [ ]:
# Try to train this!
# Let's get the data from all mhc training


## 1. Make your dataset. Make a one-hot version and a BERT version of X (aka inputs). Y (outputs) is the same

## 2. Load one of my base tensorflow models. Then make sure it can predict with the one-hot input

Don't forget early stopping, etc. as Eric did during training! Q: does this only pertain to hyperparameter tuning?

In [ ]:
# df_train [allele, peptide, measurement_value]
df_train =

# Data
X_tr, Y_tr, X_es, Y_es = self.setup_data_training(df_train)

# Train
new_model = trainf.train_mhcglobe_model(init_model, X_tr, Y_tr, X_es, Y_es, new_model_path, verbose)

## 3. Add a fully connected layer (also called linear layer) to the beginning of my tensorflow model so that it can take the larger BERT dimension input





## 4. Retrain the model in 3 above now that you have new features. The retraining in 4 should be with human data.


## 5. Compare performance of the models with one-hot or BERT input. This will give you a clue of your features will help

### Predict on the model

In [ ]:
import sequence_functions as seqf
# 1) Load Base model
model_dir = "/content/mhcglobe/model/mhcglobe/full/model14_fold13_ONE_HOT_full/"

# Both methods work!
eric_model_1b = train_functions.load_trained_mhcglobe_model(model_path=model_dir)
# eric_model_1 = tf.saved_model.load(model_dir)

# 2) Load binding data as CSV. Required columns are `allele` and `peptide`.
df_csv = '/content/mhcglobe/example/example_binding_data.csv'
prediction_cols = ['allele', 'peptide']

# 3) Use functions
pMHC_data = pd.read_csv(df_csv, usecols=prediction_cols)
X = seqf.get_XY(pMHC_data, encode_type="ONE_HOT", get_Y=False)
eric_model_1b.predict(X)

In [ ]:
pMHC_data

## 6. Hyperparameter tune with your features